import Footer from "@/components/shared/Footer/Footer";
import Navbar from "@/components/shared/Navbar/Navbar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Nazar Optics",
  description: "Generated by create next app",
};

const commonLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="overflow-hidden">
      <Navbar />
      <div className=" mt-[145px]">{children}</div>
      <Footer />
    </div>
  );
};

export default commonLayout;
